export const BOTAO_CLICADO_REQUEST = "BOTAO_CLICADO_REQUEST";
export const BOTAO_CLICADO_SUCCESS = "BOTAO_CLICADO_SUCCESS";
export const BOTAO_CLICADO_FAILURE = "BOTAO_CLICADO_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const RENEW_TOKEN_REQUEST = "RENEW_TOKEN_REQUEST";

export const PERSIST_REHYDRATE = "persist/REHYDRATE";
